version: "3.4"

networks:
  raisbbs-internal:
  apps:
    external: true

services:
  raisbbs-frontend:
    image: node:12.18-alpine
    container_name: raisbbs-frontend
    restart: "always"
    tty: true
    ports:
      - "$FRONTEND_PORT:80"
    volumes:
      - ./docker/front-end/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh
      - .:/var/dev/
      - ./docker/front-end/locks:/root/locks
    networks:
      - apps
      - raisbbs-internal
    working_dir: /var/dev
    labels:
      - "traefik.http.routers.glxorama-frontend.rule=Host(`raisbbs.com.br`)"
      - "traefik.docker.network=apps"
      - "traefik.enable=true"
      - "traefik.basic.frontend.rule=Host:raisbbs.com.br"

  raisbbsdb:
    image: mysql:8.0
    container_name: raisbbsdb
    restart: "always"
    tty: true
    ports:
      - "$MYSQL_PORT:3306"
    environment:
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
    command: --init-file /data/application/init.sql
    networks:
      - raisbbs-internal
    volumes:
      - ./docker/db_data:/var/lib/mysql
      - ./database/init.sql:/data/application/init.sql